# Hyprland config — sources modular files
# Edit the files below, not this one.

source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bindings.conf
