# Generated by set-theme — do not edit directly
$bg_color    = rgba({{ background_rgb }}, 0.95)
$inner_color = rgba({{ color0_rgb }}, 0.90)
$outer_color = rgba({{ accent_rgb }}, 0.85)
$font_color  = rgba({{ foreground_rgb }}, 1.0)
$check_color = rgba({{ color2_rgb }}, 1.0)
$fail_color  = rgba({{ color1_rgb }}, 1.0)
